---
title: "处理乳腺癌数据集"
author: "lizijin"
date: "2026-04-27"
output: html_document
---
```{r}
train_data = read.csv("../R/Breast_Cancer.csv")
str(train_data)
# 对于status, 采用0/1编码，1代表alive,0代表dead
train_data$Status <- ifelse(train_data$Status == "Alive", 1, 0)
# 对于Race,采用one-hot编码方式，
table(train_data$Race)
race_dummies = model.matrix(~Race-1,train_data)
train_data = cbind(train_data,race_dummies)
train_data$Race=NULL

```

```{r}
#继续分析Marital.Status这一列，因为不同的婚姻状态之间也是无序的，所以也是用one-hot
table(train_data$Marital.Status)
marital_dummies=model.matrix(~Marital.Status-1,train_data)
train_data = cbind(train_data,marital_dummies)
train_data$Marital.Status=NULL
```

```{r}
# 继续分析T.stage这一列
table(train_data$T.Stage)
# 从T1-T4病情越来越严重，肿瘤直径逐渐变大，是有序的
t_stage_order = c("T1","T2","T3","T4")
train_data$T.Stage=as.numeric(factor(train_data$T.Stage,levels=t_stage_order,ordered = TRUE))
```
```{r}
# 继续分析N.stage这一列
table(train_data$N.Stage)
#从n1-n3肿瘤转移越来越明显
n_stage_order = c("N1","N2","N3")
train_data$N.Stage=as.numeric(factor(train_data$N.Stage,levels=n_stage_order,ordered = TRUE))
```



```{r}
#分析x6th.stage这一列
table(train_data$X6th.Stage)
#同上有序
stage_order <- c("IIA", "IIB", "IIIA", "IIIB", "IIIC")
train_data$X6th.Stage <- as.numeric(factor(train_data$X6th.Stage, levels = stage_order,ordered = TRUE))
```

```{r}
#分析differentiate列
table(train_data$differentiate)
differentiate_order = c("Well differentiated","Moderately differentiated","Poorly differentiated","Undifferentiated")
train_data$differentiate = as.numeric(factor(train_data$differentiate,levels = differentiate_order,ordered = TRUE))
```


```{r}
#分析Grade这一列
table(train_data$Grade)
unique(train_data$Grade)
train_data$Grade <- ifelse(
  train_data$Grade == " anaplastic; Grade IV", 4,
  ifelse(train_data$Grade == "3", 3,
  ifelse(train_data$Grade == "2", 2,
  ifelse(train_data$Grade == "1", 1, NA)))
)
```

```{r}
# 对于estrogen.status，positive=1，negative=0
train_data$Estrogen.Status=ifelse(train_data$Estrogen.Status=="Positive",1,0)
# 对于Progesterone.status,positive=1,negative=0
train_data$Progesterone.Status=ifelse(train_data$Progesterone.Status=="Positive",1,0)
#对于A.stage来说,regional=1,distant=0
train_data$A.Stage=ifelse(train_data$A.Stage=="Regional",1,0)
```



```{r}
# 通过计算阳性比例
train_data$Positive_Ratio <- train_data$Reginol.Node.Positive / 
                              train_data$Regional.Node.Examined
train_data$Regional.Node.Examined=NULL
train_data$Reginol.Node.Positive = NULL
```



```{r}
# 对Age列,Tumor.Size列，Survival.Months列做z-score scaling
Age_scaled <- as.numeric(scale(train_data$Age))
train_data$Age = Age_scaled

Tumor.Size_scaled <- as.numeric(scale(train_data$Tumor.Size))
train_data$Tumor.Size = Tumor.Size_scaled

Survival.Months_scaled <- as.numeric(scale(train_data$Survival.Months))
train_data$Survival.Months = Survival.Months_scaled
```

```{r}
# Now we could check the feature type
str(train_data)
```
```{r}
train_data = train_data[sample(nrow(train_data)),]
# Make sure the label is the last column in our data frame
train_data  = train_data[, c(setdiff(names(train_data), "Status"), "Status")]

train_data_split_index = 0.8*nrow(train_data)
train = train_data[1:train_data_split_index,]
test = train_data[train_data_split_index:nrow(train_data),]

X_train = train[,-ncol(train)]
y_train = train[,ncol(train)]
dim(y_train) = c(length(y_train),1)

X_test = test[,-ncol(test)]
y_test = test[,ncol(test)]
dim(y_test) = c(length(y_test),1)

# convert them to matrix to fasten later training
X_train = as.matrix(X_train,byrow=TRUE)
X_train = t(X_train)
y_train <- as.matrix(y_train, byrow=TRUE)
y_train <- t(y_train)

X_test <- as.matrix(X_test, byrow=TRUE)
X_test <- t(X_test)
y_test <- as.matrix(y_test, byrow=TRUE)
y_test <- t(y_test)

# Now we finish data prepossessing part for this breast cancer data set, and we could move on building our nn and go checking the NN_binary.R in R folder for more details~

```





